(defpackage "MUSIC-PLAYER.TESTS-LUP"
  (:use "COMMON-LISP"
	"LISP-UNIT-PROPOSAL"))

(defpackage "MUSIC-PLAYER.CONTROLLER.TESTS-LUP"
  (:use "COMMON-LISP"
	"LISP-UNIT-PROPOSAL"))

(defpackage "MUSIC-PLAYER.CODEC.TESTS-LUP"
  (:use "COMMON-LISP"
	"LISP-UNIT-PROPOSAL"))
